#!/bin/sh
# recreg: record region of screen
# depends: ffmpeg
# usage: rr <geom> <file>

REG=$1
OUTPUT=$2

usage() {
	cat <<EOF
usage: $(basename $0) [geometry] [file]
        geometry    region to record in X11 geometry format:
                    {width}x{height}+{xpos}+{ypos} e.g. 260x320+0+760
        file        output file
EOF
}

# argument checks
if [ "$1" == -h ]; then
	usage
	exit 0
fi
if [ $# -ne 2 ]; then
	usage
	exit 1
fi

# geometry format check
if echo "$REG" | grep -Ex '[0-9]+x[0-9]+\+[0-9]+\+[0-9]+' > /dev/null; then
	# nothing
	printf ''
else
	usage
	exit 1
fi

# geometry parsing logic (yeah, it's ugly)
W=${REG%%x*}
tmp=${REG##${W}x}  H=${tmp%%+*}
tmp=${REG##*${H}+} X=${tmp%%+*}
Y=${REG##*${X}+}

echo "recording screen region ${W}x${H}+${X}+${Y}..."
echo "press ctrl+c to stop recording."

ffmpeg -y -video_size ${W}x${H} -framerate 30 -f x11grab \
	-i :0.0+${X},${Y} -c:v libx264 -qp 0 -preset ultrafast "$OUTPUT" 2> /dev/null
